import { AppSettings } from '../types/settings.types';

export const DEFAULT_SETTINGS: AppSettings = {
  deepseek_api_key: '',
  google_api_key: '',
  google_sheet_id: '11VzLIg5-evMkdGBUPzFgGXiv6nTgEL4r1wc4FDn2TKQ',
  google_sheet_name: 'Sheet1',
  last_sync_time: null,
  theme: 'blue',
  dark_mode: false,
  language: 'fa',
  font_size: 16,
  show_tooltips: true,
  animations_enabled: true,
  show_kpi_cards: true,
  show_charts: true,
  show_recent_posts: true,
  show_recent_alerts: true,
  default_time_range: '7',
  auto_analysis: false,
  analysis_delay: 5,
  batch_size: '10',
  analysis_schedule: 'manual',
  auto_sync: false,
  sync_interval: '30',
  auto_cleanup: false,
  keep_posts_for: '90',
  archive_before_delete: true,
  auto_backup: 'never',
  notifications_enabled: true,
  alert_sounds: true,
  weekly_reports: false,
  report_day: 'saturday',
  report_time: '09:00',
  report_email: '',
};

export const LEGACY_KEYS_MAP: Record<string, string> = {
  google_sheet_id: 'sheetId',
  google_sheet_name: 'sheetName',
  google_api_key: 'googleApiKey',
  last_sync_time: 'lastSyncTime',
  auto_sync: 'autoSyncEnabled',
  sync_interval: 'syncInterval',
  auto_analysis: 'autoAnalysis',
  theme: 'theme',
  dark_mode: 'darkMode',
};
